import React from 'react'
import { Link } from 'react-router-dom'
import { 
  FileText, 
  ShieldCheck, 
  Lock, 
  AlertTriangle, 
  DollarSign, 
  CheckCircle2,
  ArrowLeft
} from 'lucide-react'

export function TermsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      
      {/* Back button */}
      <Link to="/" className="inline-flex items-center space-x-2 text-xs font-bold text-slate-400 hover:text-emerald-400 transition-colors">
        <ArrowLeft className="w-4 h-4" />
        <span>Return to Home</span>
      </Link>

      {/* Header */}
      <div className="space-y-3 border-b border-slate-800 pb-6">
        <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-bold">
          <FileText className="w-3.5 h-3.5" />
          <span>Legal Agreement & Escrow Terms</span>
        </div>
        <h1 className="text-3xl font-extrabold text-white">Terms of Service & Escrow Guidelines</h1>
        <p className="text-xs text-slate-400">Effective Date: September 2, 2026 · Version 1.0</p>
      </div>

      {/* Main Content */}
      <div className="glass-card rounded-3xl p-6 sm:p-10 border border-slate-800 space-y-8 text-xs text-slate-300 leading-relaxed">
        
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">1.</span>
            <span>Platform Overview & Acceptance of Terms</span>
          </h2>
          <p>
            By accessing or using ClipYard (“Platform”), whether as a Campaign Host (“Brand”) or a Short-Form Video Editor (“Clipper”), you agree to be bound by these Terms of Service. ClipYard operates an escrow-backed performance clipping marketplace connecting long-form video creators with short-form content clippers.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3 border-t border-slate-800/80 pt-6">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">2.</span>
            <span>Escrow Budget Guarantee & Upfront Funding</span>
          </h2>
          <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 space-y-2">
            <div className="flex items-center space-x-2 font-bold text-xs text-emerald-400">
              <Lock className="w-4 h-4" />
              <span>100% Upfront Escrow Rule</span>
            </div>
            <p className="text-[11px] leading-relaxed">
              All campaign budgets must be funded 100% upfront via Stripe Checkout into platform escrow before any campaign goes live. Escrow funds are strictly reserved to pay out verified views generated by clippers according to the campaign’s CPM rate.
            </p>
          </div>
          <p>
            Unspent escrow funds from paused or completed campaigns are fully refundable to the Brand owner, minus any platform transaction fees already incurred.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-3 border-t border-slate-800/80 pt-6">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">3.</span>
            <span>View Count Polling & CPM Payout Calculation</span>
          </h2>
          <p>
            View counts are automatically polled from public platform endpoints (TikTok, YouTube Shorts, Instagram Reels) via scheduled Supabase Edge Functions. Earnings per clip are calculated using the formula:
          </p>
          <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800 font-mono text-[11px] text-emerald-400">
            Earned Amount = (Verified Views ÷ 1,000) × Campaign Rate Per 1,000 Views
          </div>
          <ul className="list-disc list-inside space-y-1.5 text-slate-300 pl-2">
            <li>Earnings are capped at the campaign’s designated <strong>Max Payout Per Clip</strong>.</li>
            <li>Earnings accrue in real time to the Clipper’s in-app wallet ledger.</li>
            <li>Payouts operate on a first-verified, first-paid basis until the campaign escrow budget is exhausted.</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="space-y-3 border-t border-slate-800/80 pt-6">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">4.</span>
            <span>Anti-Fraud & View-Botting Policy</span>
          </h2>
          <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-500/20 text-rose-300 space-y-2">
            <div className="flex items-center space-x-2 font-bold text-xs text-rose-400">
              <AlertTriangle className="w-4 h-4" />
              <span>Strict Zero-Tolerance Botting Rule</span>
            </div>
            <p className="text-[11px] leading-relaxed">
              Submissions demonstrating abnormal view velocity growth (e.g. +100,000 views within 15 minutes without corresponding engagement) will be flagged automatically for manual Admin review.
            </p>
          </div>
          <p>
            If view-botting or artificial view inflation is confirmed, the submission will be rejected, accrued earnings will be forfeited back to the Brand escrow, and the Clipper account may face permanent platform suspension.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-3 border-t border-slate-800/80 pt-6">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">5.</span>
            <span>Platform Fees & Stripe Connect Withdrawals</span>
          </h2>
          <p>
            ClipYard takes a 5% platform service fee on campaign funding to cover automated polling infrastructure, escrow security, and payment processing. Clippers can withdraw available wallet balances to their bank account at any time via integrated <strong>Stripe Connect</strong>.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3 border-t border-slate-800/80 pt-6">
          <h2 className="text-base font-extrabold text-white flex items-center space-x-2">
            <span className="text-emerald-400">6.</span>
            <span>Content Rights & Intellectual Property</span>
          </h2>
          <p>
            Brands warrant that they possess all required rights, titles, and licenses to the long-form video content uploaded or linked for clipping. Clippers receive a non-exclusive license to edit and post clips solely for active campaigns on approved platforms.
          </p>
        </section>

      </div>

    </div>
  )
}
